### PR TITLE
Fix trap behavior

### PR DESCRIPTION
**Pull request by killphi**
I have done as was asked in #3262, however I couldn't get https://github.com/wayneeseguin/rvm-test to work properly.

Also, I have no idea for how to actually and properly test this change.

I did however take the liberty to rename the signal numbers into their actual names, making it a bit more readable to the human eye.

### CODE REVIEW

**Comment by mpapis** [comment]
thank you!

**Comment by jaspertandy** [comment]
Happy to test this if needed. Let me know the rvm code to pull the appropriate version and I'll do so.

**Comment by mpapis** [comment]
@jaspertandy:
```bash
rvm get head
rvm install ruby-named
```
and then CTRL+C somewhere, in another try, `killall rvm` - although you might need to find the proper shell process first and kill it manually

**Comment by mpapis** [comment]
the most important part is that the shell result code should be `!=0` check with `echo $?`

**Pull request merged**
