### PR TITLE
Use the CDN for binaries. Related to rvm/rvm-site-setup#1

### PR DESCRIPTION
**Pull request by jrgifford**

### CODE REVIEW

**Comment by jrgifford** [comment]
@mpapis Whenever you have a moment, here ya go. Should be all good to go.

**Comment by mpapis** [comment]
thank you!

**Comment by shtirlic** [comment]
Hi, I am getting something strange 
```
curl -vvv https://rvm_io.global.ssl.fastly.net/binaries/centos/6/x86_64/ruby-2.1.5.tar.bz2                                    130 ↵
*   Trying 23.235.43.249...
* Connected to rvm_io.global.ssl.fastly.net (23.235.43.249) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: a.ssl.fastly.net
* Server certificate: DigiCert SHA2 High Assurance Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> GET /binaries/centos/6/x86_64/ruby-2.1.5.tar.bz2 HTTP/1.1
> User-Agent: curl/7.41.0
> Host: rvm_io.global.ssl.fastly.net
> Accept: */*
>
< HTTP/1.1 503 Internal Server Error
< Date: Wed, 15 Apr 2015 18:51:41 GMT
< Server: Varnish
< Retry-After: 0
< Error-Reason: loop detected
< X-Forwarded-From: cacheams4125AMS
< Via: 1.1 varnish
< Fastly-Restarts: 1
< Content-Length: 31
< Accept-Ranges: bytes
< Via: 1.1 varnish
< X-Served-By: cache-ams4125-AMS
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1429123901.599954,VS0,VE5
< Connection: close
<
* Closing connection 0
 Loop occurred: cacheams4125AMS%
```

**Comment by jrgifford** [comment]
I think this is related to fastly - getting it directly from RVM.io worked fine for me.

@mpapis?

**Comment by shtirlic** [comment]
@jrgifford yes, directly via `mount -r`  is working

**Comment by mpapis** [comment]
fixing it now

**Comment by mpapis** [comment]
yep, missed to activate the configuration, should be good in few

**Comment by mpapis** [comment]
btw. we should switch back to rvm.io as we use fastly now for main IP

**Pull request merged**
