### PR TITLE
Railsexpress patches for ruby 2.2.1

### PR DESCRIPTION
**Pull request by skaes**
can you please merge?

### CODE REVIEW

**Comment by mpapis** [comment]
thank you and sorry for the delay, next time please mention my nick as I have disabled notifications on this repository => http://niczsoft.com/2015/02/changes-in-my-open-source-life/

**Comment by skaes** [comment]
@mpapis no problem. I would offer to merge my patches myself, if I had push rights to the repository. However, I don't want to become a full maintainer.

**Comment by mpapis** [comment]
oh you would have push rights already if it were up to me, but @wayneeseguin is very busy recently and we need to wait for him to add you, btw. invited you to RVMs slack in case you have any questions or would like to hurry up next release

**Comment by skaes** [comment]
thx.

**Pull request merged**
